name: lets_get_serious
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.14
  google_nav_bar: ^5.0.7

  shared_preferences: ^2.3.5

  sentry_flutter: ^8.12.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  image_picker: ^1.1.2
  firebase_remote_config: ^5.3.1
  share_plus: ^10.1.4
  flutter_localizations:
    sdk: flutter
  postgres: ^2.4.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/credits_icons/

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
        - asset: assets/fonts/Product Sans Bold Italic.ttf
          style: italic
        - asset: assets/fonts/Product Sans Bold.ttf
          weight: 400
        - asset: assets/fonts/Product Sans Italic.ttf
          weight: 400
          style: italic
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/to/font-from-package
